---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connaisseur
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: connaisseur
      repoURL: https://sse-secure-systems.github.io/connaisseur/charts
      targetRevision: 2.7.0

      helm:
        valueFiles:
        - $values/release/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-connaisseur.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: connaisseur

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
